Features/freelance hero
societe-coton/website pull request #15
Opened 2022-01-20 06:51 UTC by Benjamin1er

- [ ] Header button is now switchable
- [ ] Changed Hero content
- [ ] Created Offer Section
- [ ] Created Pricing Section
- [ ] Created Tooling Section

2022-01-21 07:42 UTC, jbbeuzelin requested changes

2022-01-21 07:42 UTC, jbbeuzelin commented on front/src/components/Header/Header.tsx
> +    if (window.scrollY >= 40) {
For better readability, avoid if/else when possible: 

```
const isYScrollActivated = window.scrollY >= 40;
setScrollY(isYScrollActivated);
```

2022-01-22 15:51 UTC, pg-bdlcm commented on front/src/components/Header/Header.tsx
> +            to={window.location.href.indexOf('freelances') > -1 ? '/' : '/freelances'}
to avoid bug in the futur, set freelances path in a variable
like :

2022-01-22 15:59 UTC, pg-bdlcm commented on front/src/helpers/customcss.ts
> +export interface ICustomCSS {
Top le typage, mais problème de naming, ICustomCSS est valable uniquement pour sa propriété style. J'aurai plutot utilisé le naming suivant :
```
export interface IHeroContent {
  h1: string;
  h2: string;
  button: string;
  style: ICustomCSS;
}

interface ICustomCSS {
  backgroundColor: string; 
  display?: string;
}
```
à modifier aussi dans le fichier Hero.tsx ou il est appelé

2022-01-22 16:01 UTC, pg-bdlcm commented on front/src/pages/index.tsx
> +      <Hero customCSSCompany={customCSSCompany} />
pour simplifier le code de Hero je te propose l'appel suivant :
<Hero content={customCSSCompany} />

2022-01-22 16:02 UTC, pg-bdlcm commented on front/src/pages/freelances.tsx
> +      <Hero customCSSFreelance={customCSSFreelance} />
pour simplifier le code de Hero je te propose l'appel suivant :
<Hero content={customCSSFreelance} />

2022-01-22 16:04 UTC, pg-bdlcm commented on front/src/helpers/customcss.ts
> +export const customCSSFreelance: ICustomCSS = {
Soucis de naming de la variable ici, customCSSFreelance n'est pas que du css custom, je te propose :
```
export const freelanceHeroContent
...
export const companyHeroContent
```

2022-01-22 16:06 UTC, pg-bdlcm commented on front/src/components/Hero/Hero.tsx
> +  customCSSFreelance?: ICustomCSS;
dans la suite ici tu devrais du coup changer pour :
```
interface IProps {
    content: ICustomCSS;
}
```

2022-01-22 16:07 UTC, pg-bdlcm commented on front/src/components/Hero/Hero.tsx
> +      <h1>{customCSSFreelance ? customCSSFreelance.h1 : customCSSCompany.h1}</h1>
du coup ici tout devient plus simple :
```
<h1>{content.h1}</h1>
<h2>{content.h2}</h2>
...
```

2022-01-22 16:07 UTC, pg-bdlcm commented on front/src/components/Hero/Hero.tsx
> +  const { customCSSFreelance } = props;
la suite :
```
const { content } = props;
```

2022-01-22 16:09 UTC, pg-bdlcm commented on front/src/gatsby-config.ts
>  const gatsbyConfig: GatsbyConfig = {
Peut-etre un fichier qui ne fait pas partie de cette PR (plutot de la PR Cookie) mais tu peux le laisser ce n'est pas grave

2022-01-22 16:11 UTC, pg-bdlcm commented
Une PR qui t'a fait joué avec les props et leur types, tu apprends vite c'est top
Ne pas hésiter a changé un naming si il ne devient plus adapté (customCSS par exemple)

2022-01-23 13:24 UTC, Benjamin1er commented on front/src/pages/index.tsx
> +      <Hero customCSSCompany={customCSSCompany} />
Beau suspens, j'ai fini par trouver 😉

2022-01-25 07:10 UTC, pg-bdlcm commented on front/src/components/Header/Header.tsx
>      style === theme.colors.green ? setStyle(theme.colors.blue) : setStyle(theme.colors.green);
c'est dur de comprendre la logique de `style === theme.colors.green`, en pratique on veut du bleu ou du vert en fonction de la variable freelance pas de la variable style.
Plutôt :
```
if(freelance) setStyle(theme.colors.green)
else setStyle(theme.colors.blue)
// or
freelance ? setStyle(theme.colors.green) : setStyle(theme.colors.blue)

setFreelance(!freelance)
```

2022-01-25 07:10 UTC, pg-bdlcm commented on front/src/components/Hero/Hero.tsx
> +          style={{ backgroundColor: content.style.backgroundColor }}
👍

2022-01-25 09:16 UTC, jbbeuzelin approved these changes

2022-01-25 10:05 UTC, merged